name: Generate Snake

on:
  schedule: # Runs at 9:00 AM UTC every day
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: MwesigwaElijahK
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
